### ISSUE TITLE
Borders come up as a unknown command

### ISSUE THREAD

**Issue by OdiousImp2604** [fluix-dev/sway-borders#64]
### Please fill out the following:
- **Sway Version:**
  - `swaymsg version 1.8-dev-55702663 (Jun  6 2022, branch 'master')`

- **Debug Log:**
  - https://dpaste.com/G75Y7X6EW
  - Pastebin said my log was offensive for some reason

- **Configuration File:**
```
border_images.focused ~/.config/sway/borders/focused.png
border_images.focused_inactive ~/.config/sway/borders/focused_inactive.png
border_images.unfocused ~/.config/sway/borders/unfocused.png
border_images.urgent ~/.config/sway/borders/urgent.png

```

- **Description:**
  - Installed sway-borders-git and wlroots-git from AUR
  - Rebooted
  - Error popped up

**Comment by fluix-dev** [comment]
I believe your issue is an unclosed `bar` block. I see the following in your log:

```
00:00:00.115 [DEBUG] [sway/config.c:878] Entering block 'bar'
```

But no "Exiting block 'bar'" as with other blocks (like `exec_always`). In future, or if this doesn't solve your issue, please make sure to either paste your configuration file in bug reports too :)

---

> Pastebin said my log was offensive for some reason

Pastebin isn't a great paste site for numerous other reasons (having ads, etc.) anyways. Stick with the alternatives.

**Comment by OdiousImp2604** [comment]
That was an amazing catch fluix-dev! I have no clue how you saw that. Sorry for troubling your with a problem that wasn't at all do with sway-borders and rather just me being stupid.
