### ISSUE TITLE
Consider contributing your patch to swayfx and closing this repo

### ISSUE THREAD

**Issue by Kommynct** [fluix-dev/sway-borders#78]
It doesn't have any of the features of swayfx and quite frankly, there's way more work done there. You might want to close this down and contribute to them instead.

https://github.com/WillPower3309/swayfx

**Comment by fluix-dev** [comment]
I mean, I do have plans to archive this repository because I don't personally use rounded borders anymore and don't really plan on working on this project anymore, but quite frankly suggesting someone _close down_ a project and contribute to an alternative isn't the kindest thing to hear. Probably not the way you meant it so no worries, just sharing how I felt :)

(IIRC) I already suggested some shader improvements to rounded borders in swayfx in a comment (related to smoother transitions using some transparency), but I believe they were eventually superseded. I don't think there's much from this repository to contribute because rounded borders are, as I understand, already supported there, but feel free to correct me if I'm wrong.
